# Generated by Django 2.1.7 on 2019-05-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='vendor_comments',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
