# Generated by Django 2.1.7 on 2019-05-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_vendor_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='vendor_comments',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
