# Generated by Django 2.1.7 on 2019-05-02 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('featuredproduct', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='aroma',
            new_name='fp',
        ),
    ]
