# Generated by Django 2.1.7 on 2019-05-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featuredproduct', '0003_fp_qtytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='fp',
            name='variation1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fp',
            name='variation2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fp',
            name='variation3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fp',
            name='variation4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fp',
            name='variation5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fp',
            name='variation6',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fp',
            name='variation7',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fp',
            name='variation8',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fp',
            name='variation9',
            field=models.TextField(blank=True),
        ),
    ]
