# Generated by Django 2.1.7 on 2019-05-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aromas', '0002_aroma_botanicalname'),
    ]

    operations = [
        migrations.AddField(
            model_name='aroma',
            name='maxprice',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
