# Generated by Django 2.1.7 on 2019-04-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('florals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='floral',
            name='longdesc',
            field=models.TextField(blank=True),
        ),
    ]
