# Generated by Django 2.1.7 on 2019-05-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('florals', '0002_floral_longdesc'),
    ]

    operations = [
        migrations.AddField(
            model_name='floral',
            name='maxprice',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
