# Generated by Django 2.1.7 on 2019-04-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='essential',
            name='botanicalname',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='essential',
            name='origin',
            field=models.TextField(blank=True),
        ),
    ]
