# Generated by Django 2.1.7 on 2019-04-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0002_auto_20190425_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essential',
            name='price',
            field=models.IntegerField(blank=True),
        ),
    ]
