# Generated by Django 2.1.7 on 2019-04-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0003_auto_20190427_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='essential',
            name='maxprice',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='essential',
            name='price',
            field=models.IntegerField(),
        ),
    ]
