# Generated by Django 2.1.7 on 2019-05-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0004_auto_20190427_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='essential',
            name='variation',
            field=models.TextField(blank=True),
        ),
    ]
