# Generated by Django 2.1.7 on 2019-05-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attars', '0002_attar_maxprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attar',
            name='maxprice',
            field=models.IntegerField(blank=True),
        ),
    ]
